name: Add Date to Commit Message

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  add_date_to_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set commit date
        run: |
          date=$(date +%Y-%m-%d)
          git log -1 --pretty=%B > commit_message.txt
          echo -e "\nDate: $date" >> commit_message.txt
          cat commit_message.txt | git commit -F -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
