name: Add Date to Commit Message

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  add_date_to_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set git user
        run: |
          git config --global user.name "anuraago"
          git config --global user.email "anuore125@gmail.com"

      - name: Set commit date
        run: |
          date=$(date +%Y-%m-%d)
          echo -e "\nDate: $date" >> commit_message.txt
          git add commit_message.txt
          git commit -m "Update commit message with date"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
